const corrections = {
    subRegions: {
        Antarctica: [
            "Antarctica",
        ],
        Arctic: [
            'Canada',
            'Norway',
            'Russia',
            'Svalbard and Jan Mayen',
            'Sweden',
            'United States',
        ],
        "Southern Ocean": [
            'Bouvet Island',
            'Falkland Islands',
            'French Southern and Antarctic Lands',
            'Heard Island and McDonald Islands',
            'South Georgia',
        ],
        "Atlantic Ocean": [
            'Bermuda',
            'Cape Verde',
            'Faroe Islands',
            'Iceland',
            'Saint Helena, Ascension and Tristan da Cunha',
            'Saint Pierre and Miquelon'
        ],
        "Indian Ocean": [
            'British Indian Ocean Territory',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Maldives',
            'Mauritius',
            'Seychelles',
            'Sri Lanka',
        ],
        "Australia & New Zealand": [
            'Australia',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'New Zealand',
        ],
        "Polynesia": [
            "American Samoa",
            'Cook Islands',
            'French Polynesia',
            'Niue',
            'Pitcairn Islands',
            'Samoa',
            'Tokelau',
            'Tonga',
            'Tuvalu',
            'United States Minor Outlying Islands',
            'Wallis and Futuna',
        ],
        "Melanesia": [
            'Fiji',
            'New Caledonia',
            'Papua New Guinea',
            'Solomon Islands',
            'Vanuatu',
        ],
        "Micronesia": [
            'Guam',
            'Kiribati',
            'Marshall Islands',
            'Micronesia',
            'Nauru',
            'Northern Mariana Islands',
            'Palau',
            'United States Minor Outlying Islands',
        ],
        "Caribbean": [
            "Anguilla",
            "Antigua and Barbuda",
            'Aruba',
            'Bahamas',
            'Barbados',
            'British Virgin Islands',
            'Caribbean Netherlands',
            'Cayman Islands',
            'Cuba',
            'Curaçao',
            'Dominica',
            'Dominican Republic',
            'Grenada',
            'Guadeloupe',
            'Haiti',
            'Jamaica',
            'Martinique',
            'Montserrat',
            'Puerto Rico',
            'Saint Barthélemy',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Martin',
            'Saint Vincent and the Grenadines',
            'Sint Maarten',
            'Trinidad and Tobago',
            'Turks and Caicos Islands',
            'United States Minor Outlying Islands',
            'United States Virgin Islands',
        ],
        "Northern America": [
            'Canada',
            'Greenland',
            'Mexico',
            'Saint Pierre and Miquelon',
            'United States',
        ],
        "Central America": [
            'Belize',
            'Costa Rica',
            'El Salvador',
            'Guatemala',
            'Nicaragua',
            'Panama'
        ],
        "South America": [
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Colombia',
            'Ecuador',
            'Falkland Islands',
            'French Guiana',
            'Guyana',
            'Paraguay',
            'Peru',
            'Suriname',
            'Uruguay',
            'Venezuela',
        ],
        "Western Europe": [
            "Andorra",
            'Belgium',
            'France',
            'Guernsey',
            'Ireland',
            'Isle of Man',
            'Jersey',
            'Luxembourg',
            'Monaco',
            'Netherlands',
            'United Kingdom',
        ],
        "Northern Europe": [
            "Åland Islands",
            'Denmark',
            'Estonia',
            'Farore Islands',
            'Finland',
            'Guernsey',
            'Iceland',
            'Ireland',
            'Isle of Man',
            'Latvia',
            'Lithuania',
            'Norway',
            'Sweden',
            'United Kingdom',
        ],
        "Central Europe": [
            'Austria',
            'Czechia',
            'Germany',
            'Hungary',
            'Liechtenstein',
            'Poland',
            'Slovakia',
            'Slovenia',
            'Switzerland',
            'Uzbekistan',
        ],
        "Eastern Europe": [
            'Azerbaijan',
            'Belarus',
            'Georgia',
            'Kazakhstan',
            'Moldova',
            'Romania',
            'Russia',
            'Ukraine',
        ],
        "Southern Europe": [
            "Albania",
            "Andorra",
            'Bosnia and Herzegovina',
            'Bulgaria',
            'Croatia',
            'Cyprus',
            'Gibraltar',
            'Greece',
            'Italy',
            'Kosovo',
            'Malta',
            'Moldova',
            'Montenegro',
            'North Macedonia',
            'Portugal',
            'Romania',
            'San Marino',
            'Serbia',
            'Slovenia',
            'Spain',
            'Vatican City',
        ],
        "Western Asia": [
            'Armenia',
            'Azerbaijan',
            'Bahrain',
            'Cyprus',
            'Georgia',
            'Iran',
            'Iraq',
            'Israel',
            'Jordan',
            'Kuwait',
            'Lebanon',
            'Oman',
            'Palestine',
            'Qatar',
            'Saudi Arabia',
            'Syria',
            'Turkey',
            'United Arab Emirates',
            'Yemen',
        ],
        "Siberia": [
            'Russia'
        ],
        "Central Asia":[
            "Afghanistan",
            'China',
            'India',
            'Iran',
            'Kazakhstan',
            'Kyrgyzstan',
            'Mongolia',
            'Pakistan',
            'Russia',
            'Tajikistan',
            'Turkmenistan',
        ],
        "Eastern Asia": [
            'China',
            'Hong Kong',
            'Japan',
            'Macau',
            'Mongolia',
            'North Korea',
            'South Korea',
            'Taiwan',

        ],
        "Southeastern Asia": [
            'Brunei',
            'Cambodia',
            'Indonesia',
            'Laos',
            'Malaysia',
            'Myanmar',
            'Philippines',
            'Singapore',
            'Thailand',
            'Vietnam',
        ],
        "Southern Asia": [
            "Afghanistan",
            'Bangladesh',
            'Bhutan',
            'India',
            'Maldives',
            'Nepal',
            'Pakistan',
            'Sri Lanka',
        ],
        "Northern Africa": [
            "Algeria",
            'Chad',
            'Egypt',
            'Libya',
            'Mali',
            'Mauritania',
            'Morocco',
            'Niger',
            'Sudan',
            'Tunisia',
            'Western Sahara',
        ],
        "Western Africa": [
            'Benin',
            'Burkina Faso',
            'Cape Verde',
            'Gambia',
            'Ghana',
            'Guinea',
            'Guinea-Bissau',
            'Ivory Coast',
            'Liberia',
            'Mali',
            'Mauritania',
            'Niger',
            'Nigeria',
            'Senegal',
            'Sierra Leone',
            'Togo',
        ],
        "Central Africa": [
            "Angola",
            'Cameroon',
            'Central African Republic',
            'Chad',
            'DR Congo',
            'Equatorial Guinea',
            'Gabon',
            'Republic of the Congo',
            'São Tomé and Principe',
            'Zambia'
        ],
        "Eastern Africa": [
            'Burundi',
            'Comoros',
            'Djibouti',
            'Eritrea',
            'Ethiopia',
            'Kenya',
            'Madagascar',
            'Malawi',
            'Mauritius',
            'Mayotte',
            'Mozambique',
            'Réunion',
            'Rwanda',
            'Seychelles',
            'Somalia',
            'South Sudan',
            'Sudan',
            'Tanzania',
            'Uganda',
            'Zambia',
            'Zimbabwe'
        ],
        "Southern Africa": [
            'Botswana',
            'Comoros',
            'Eswatini',
            'Lesotho',
            'Madagascar',
            'Malawi',
            'Mayotte',
            'Mozambique',
            'Namibia',
            'Réunion',
            'South Africa',
            'Zambia',
            'Zimbabwe'
        ]
    }
}

corrections.regions = {
    Americas: [
        ...corrections.subRegions.Caribbean,
        ...corrections.subRegions['Northern America'],
        ...corrections.subRegions['Central America'],
        ...corrections.subRegions['South America']
    ],
    Europe: [
        ...corrections.subRegions['Northern Europe'],
        ...corrections.subRegions['Western Europe'],
        ...corrections.subRegions['Central Europe'],
        ...corrections.subRegions['Southern Europe'],
        ...corrections.subRegions['Eastern Europe']
    ],
    Africa: [
        ...corrections.subRegions['Northern Africa'],
        ...corrections.subRegions['Western Africa'],
        ...corrections.subRegions['Central Africa'],
        ...corrections.subRegions['Southern Africa'],
        ...corrections.subRegions['Eastern Africa']
    ],
    Asia: [
        ...corrections.subRegions['Siberia'],
        ...corrections.subRegions['Western Asia'],
        ...corrections.subRegions['Central Asia'],
        ...corrections.subRegions['Southern Asia'],
        ...corrections.subRegions['Eastern Asia'],
        ...corrections.subRegions['Southeastern Asia']
    ],
    Oceania: [
        ...corrections.subRegions['Polynesia'],
        ...corrections.subRegions['Micronesia'],
        ...corrections.subRegions['Melanesia'],
        ...corrections.subRegions['Australia & New Zealand'],
    ],
    "Antarctic": [
        ...corrections.subRegions['Antarctica'],
        ...corrections.subRegions['Southern Ocean']
    ],
    "Atlantic": [
        ...corrections.subRegions['Atlantic Ocean']
    ],
    "Indian Ocean": [
        ...corrections.subRegions['Indian Ocean']
    ]
}

corrections.names = [
    ['Åland Islands', 'Åland'],
    ['Eswatini', 'eSwatini'],
    ['Republic of the Congo', 'Congo-Brazzaville'],
    ['DR Congo', 'Congo-Kinshasa']
]

corrections.microRegions = {
    "Middle east": [
        'Turkey',
        'Syria',
        'Lebanon',
        'Israel',
        'Palestine',
        'Cyprus',
        'Egypt',
        'Saudi Arabia',
        'Oman',
        'Yemen',
        'United Arab Emirates',
        'Qatar',
        'Bahrain',
        'Kuwait',
        'Iraq',
        'Iran',
        'Jordan'
    ],
    "Scandinavia": ['Denmark', 'Norway', 'Sweden'],
    "Iberian Peninsula": ['Spain', 'Portugal', 'Andorra'],
    "Low Countries": ['Belgium', 'Netherlands', 'Luxembourg'],
    'Balkan Peninsula': [
        'Croatia',
        'Bosnia and Herzegovina',
        'Serbia',
        'Kosovo',
        'Montenegro',
        'Albania',
        'North Macedonia',
        'Greece',
        'Bulgaria'
    ],
    'Indochina': ['Vietnam', 'Cambodia', 'Laos', 'Thailand'],
    'Arabian Peninsula': ['Bahrain', 'Iraq', 'Jordan', 'Kuwait', 'Qatar', 'Oman', 'Yemen', 'Saudi Arabia', 'United Arab Imerates'],
    'Horn of Africa': ['Ethiopia', 'Eritrea', 'Djibouti', 'Somalia', 'Somaliland'],
    'Baltic Countries': ['Lithuania', 'Latvia', 'Estonia']
}

export default corrections